server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

logging:
  level:
    org.springframework.web: WARN

jwt:
  secret: ${JWT_SECRET:SGVsbG9Xb3JsZFNlY3JldEtleUZvckp3dFRva2VuQXV0aGVudGljYXRpb25QdXJwb3Nlcw==}

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs
  show-actuator: false
  packages-to-scan: com.brandon.finance