server:
  port: 8082

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml

  jpa:
    hibernate:
      ddl-auto: none

app:
  api-url: http://localhost:8082